

export const GRAPHCMS_API_AUTHOR_NAME = 'nfg.api'
export const GRAPHCMS_INTERNAL_RATE_LIMIT_COUNT = 5 // in 30 seconds
export const GRAPHCMS_INTERNAL_RATE_LIMIT_MS = 30000

export default {
  GRAPHCMS_API_AUTHOR_NAME,
  GRAPHCMS_INTERNAL_RATE_LIMIT_COUNT,
  GRAPHCMS_INTERNAL_RATE_LIMIT_MS
}