
name: 'Auto: Deploy Master'
on:
  push:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
jobs:
  build_and_deploy_infrastructure:
    name: Build and Deploy Env Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
      - run: terraform init
        working-directory: ./env-infrastructure
      - run: terraform workspace select staging
        working-directory: ./env-infrastructure
      - run: terraform apply -auto-approve -var-file staging.tfvars
        working-directory: ./env-infrastructure
  build_and_deploy_api:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    needs: build_and_deploy_infrastructure
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: api/yarn.lock
      - run: yarn
        working-directory: ./api
      - run: yarn build
        working-directory: ./api
      - run: yarn make-manifest
        working-directory: ./api
      - run: terraform init
        working-directory: ./api/tf
      - run: terraform workspace select staging
        working-directory: ./api/tf
      - run: terraform apply -auto-approve -var-file staging.tfvars
        working-directory: ./api/tf